[package]
name = "aoc-2026"
authors = ["Tommi Pakarinen"]
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
z3 = { version = "0.19.6", features = ["gh-release"], optional = true }

[features]
z3 = ["dep:z3"]

[[bin]]
name = "10"

required-features = ["z3"]
